#!/bin/zsh

TMP=`mktemp`

for url in $@
do
    echo "Extracting from $url..."
    test -e $TMP.index || curl -s $url > $TMP.index

    # get title
    TITLE=`perl -Mcommon::sense -MHTML::Entities -ne 'if ( /(?<=<h1 id="gn">)([^<]+)/ ) { my $a = decode_entities($1); $a =~ s/[\/\\|]/./g; print "$a\n" }' < $TMP.index`

    echo $TITLE
    test -e $TITLE.cbz && exit

    # pagination
    echo $url > $TMP.pages
    perl -Mcommon::sense -ne '/(?<=href=")([^"]*?p=\d+)/; say $1 if $1' $TMP.index | sort -u >> $TMP.pages

    i=1
    
    cat $TMP.pages | while read page
    do
	test -e $TMP.page.$i || curl -s $page > $TMP.page.$i

	# parse page for images
	test -e $TMP.images.$i ||
	    perl -ne 'my @matches = m/(?<=href=")([^"]*?\d-\d+)/g; foreach my $a (@matches) { print "$a\n"; }' < $TMP.page.$i | tee $TMP.images.$i

	cat $TMP.images.$i | while read link
	do
	    curl -s $link | perl -Mcommon::sense -ne '/(?<=<img id="img" src=")([^"]+)/; say $1 if $1' | wget -q -nc -i -
	    echo -n .
	done
	
	((i=i + 1))
    done

    echo ''
    
    # zip 'em
    \zip -dd -m $TITLE.zip *.jpg
    \zip -dd -m $TITLE.zip *.png
    mv $TITLE.zip $TITLE.cbz
    
done

rm -f $TMP $TMP.*
