#!/usr/bin/perl 

use common::sense;

my $index_url = $ARGV[0];

my $index = qx{curl -s '$index_url'};

my %files;

foreach ( split /\n/, $index ) {
	chomp;chomp;

	next unless m!href="(/game-soundtracks/album/[^"]+)!;

	my $fn = qq{https://downloads.khinsider.com$1};

	next unless $fn =~ m/\.(mp3|ogg|wav)$/i;
	
	next if $files{$fn};

	$files{$fn} = 1;

}

if ( !scalar %files ) {
	die $index;
}

printf("downloading %d files\n", scalar(keys %files));

foreach ( sort keys %files ) {

	my $dl = qx{curl -s '$_'};

	my @lines = split /\n/, $dl;

	my ($winner) = grep { $_ =~ "Click here to download" } @lines;
	$winner =~ m!href="([^"]+)"!;

	qx{wget -c $1};

}
